version: '3.9'
services:
        mundo-backend:
                container_name: mundo-backend
                build:
                        context: .
                restart: always
                ports:
                        - 80:80
                environment:
                        PORT: 3000
                healthcheck:
                        test: "exit 0"

